#!/usr/bin/expect

interp create -safe safeInterp
safeInterp invokehidden source gedi_exp.exp
lassign [safeInterp eval {list $timeout $connect}] timeout connect

set delay [lindex $argv 0]
spawn bash $connect lgbu

expect "ssword:"
sleep 1
send -- "ubuntu\r"
expect "ubuntu"
send -- "rm -R downloads/lgbu_logs*; bash auto/mysqlbkp_recent.sh $delay\r"
send -- "ubuntu\r"
expect "Done"
send -- "exit\r"

expect eof