---
site_config:
  bgbu:
    gateway_addres: 172.19.154.14
    host: 172.19.162.115
    netmask: 24
  lgbu:
    gateway_addres: 172.21.68.120
    host: 172.21.68.120
    netmask: 24
  nigbu:
    gateway_addres: 172.22.32.254
    host: 172.21.152.120
    netmask: 24
  magbu:
    gateway_addres: 172.22.32.254
    host: 172.22.31.120
    netmask: 24
server:
  username: slopeuser
  password: Acc3lerometer!
  database: edcslopedb

